application: iapcb-demo
version: 1-1
runtime: python27
threadsafe: no

api_version: 1

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /.*
  script: main.py
